config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => redirect("/users/sign_in")

  resources :posts do
    resources :comments
  end


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :context, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["context", "created_at", "id", "post_id", "updated_at", "user_id"]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show destroy]
  load_and_authorize_resource

  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find_by(id: params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @post
    else
      flash[:notice] = @comment.errors.full_messages
      redirect_to @post, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
    @post = Post.find_by(id: params[:post_id])
    @comment = Comment.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:post_id])
    @comment = @post.comments.find_by(id: params[:id])
    if @comment.update(comment_params)
      redirect_to @post, notice: 'Comment updated successfully.'
    else
      render 'edit'
    end
  end

  def index
    @comment = Comment.all
  end

  def destroy
    @comment.destroy
    redirect_to posts_path, status: :see_other
  end

  private

  def set_comment
    @comment = Comment.find_by(id: params[:id])
  end

  def comment_params
    params.require(:comment).permit(:context)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<h1>Comment Edit</h1>



<%= form_for [@post, @comment] do |f| %>

  <div class="field">
    <%= f.label :context %>
    <%= f.text_field :context %>
  </div>
  <%= f.submit 'Update Comment' %>
<% end %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Context</th>
      <th>post_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comment.each do |comment| %>
      <tr>
        <td><%= comment.context %></td>
        <td><%= comment.post_id %></td>
        <td><%= link_to "view", comment %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/comments/new.html.erb
<h1>Comment Create</h1>

<%= form_with model: @comment do |form| %>

  <div>
    <%= form.label :context%><br>
    <%= form.text_field :context %>
  </div>

  <div>
    <%= hidden_field_tag 'post_id', @post.id  %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

<%= button_to "Sign out", destroy_user_session_path, method: :delete %>

app/views/comments/show.html.erb
<strong>id: </strong> <%= @comment.id %><br />
<strong>Context: </strong> <%= @comment.context %><br />
<strong>Post_id: </strong> <%= @comment.post_id %><br />
<td><%= link_to "edit", edit_comment_path(@comment) %></td>
<li><%= link_to "Destroy", comment_path(@comment), data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
} %></li>