config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => redirect("/users/sign_in")

  resources :posts do
    resources :comments
  end


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :blog_pic
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :tittle, :context, presence: true


  def self.ransackable_attributes(auth_object = nil)
    ["context", "created_at", "id", "tittle", "updated_at", "user_id", "blog_pic"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["comments", "user"]
  end

  self.per_page = 2
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: %i[show edit update destroy]

  load_and_authorize_resource

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post
    else
      flash[:notice] = @post.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @comment = Comment.new
    render :show
  end

  def edit
  end

  def update
    if @post.update(post_params)
        redirect_to @post
    else
      flash[:notice] = @post.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  def index
    if current_user.role == 'admin'
      @post = Post.paginate(page: params[:page])
    else
      @post = current_user.posts.paginate(page: params[:page])
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, status: :see_other
  end

  private

  def set_post
    @post = Post.find_by(id: params[:id])
  end

  def post_params
    params.require(:post).permit(:tittle, :context, :blog_pic )
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Post Update</h1>
<p><%= flash[:notice] %></p>

<%= form_with model: @post do |form| %>

  <div>
    <%= form.label :Tittle%><br>
    <%= form.text_field :tittle %>
  </div>

  <div>
    <%= form.label :Context %><br>
    <%= form.text_field :context %>
  </div>
  <div>
  <%= form.label :blog_pic %>
  <%= form.file_field :blog_pic %>
</div>
  <div>
    <%= form.submit %>
  </div>

<% end %>

<%= button_to "Sign out", destroy_user_session_path, method: :delete %>

app/views/posts/index.html.erb
<h1>Posts</h1>


<table>
  <thead>
    <tr>

      <th>Id</th>
      <th>Tittle</th>
      <th>Context</th>
      <th>User_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post.each do |post| %>
      <tr>
        <td>
          <% if post.blog_pic.attached? %>
            <%= image_tag post.blog_pic, height:'50px', width: '50px' %>
          <% end %>
        </td>
        <td><%= post.id %></td>
        <td><%= post.tittle %></td>
        <td><%= post.context %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to "view", post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div><%= flash[:notice] %></div>

<div class="pagination">
  <%= will_paginate @post %>
</div>

<%= button_to "Sign out", destroy_user_session_path, method: :delete %>

<%= button_to "create post", new_post_path, method: :get if current_user.role=="user" %>

app/views/posts/new.html.erb
<h1>Post Create</h1>
<p><%= flash[:notice] %></p>
<%= form_with model: @post, html: { multipart: true } do |form| %>

  <div>
    <%= form.label :Tittle%><br>
    <%= form.text_field :tittle %>
  </div>

  <div>
    <%= form.label :Context %><br>
    <%= form.text_field :context %>
  </div>
  <div>
    <%= form.label :blog_pic %>
    <%= form.file_field :blog_pic %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

<%= button_to "Sign out", destroy_user_session_path, method: :delete %>

app/views/posts/show.html.erb
  <strong>id: </strong> <%= @post.id %> <br/>
  <strong>Tittle: </strong> <%= @post.tittle %><br />
  <strong>Context: </strong> <%= @post.context %><br />
  <strong>User_id: </strong> <%= @post.user_id %><br />
  <td><%= link_to "edit", edit_post_path(@post) if current_user.id==@post.user_id || current_user.role=="admin" %></td>
  <td><%= link_to "Destroy", post_path(@post), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } if current_user.id==@post.user_id  || current_user.role=="admin" %></td>

  <h1>Comment</h1>
  <% if current_user.role=="user" %>
    <p><%= flash[:notice] %></p>
    <%= form_with model: @comment, url: post_comments_path(@post) do |f| %>
      <%= f.text_field :context, placeholder: 'Enter your comment here...' %>
      <%= f.submit 'Create comment' %>
    <% end %>
  <% end %>
  <hr>
  <% @post.comments.each do |comment| %>
    <strong>id: </strong> <%= comment.id %><br />
    <strong>Context: </strong> <%= comment.context %><br />
    <strong>Post_id: </strong> <%= comment.post_id %><br />

    <td><%= link_to "edit", edit_post_comment_path(@post,comment) if current_user.id==comment.user_id  || current_user.role=="admin" %></td>
    <td><%= link_to "Destroy", post_comment_path(@post,comment), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } if current_user.id==comment.user_id  || current_user.role=="admin" %></td><br><hr>

  <% end %>